# Tämä tiedosto suoritetaan, kun main-branchiin tulee muutoksia
# Pushaa express-kansion sisällön haluttuun repositorioon
# Dokumentaatio täällä: https://cpina.github.io/push-to-another-repository-docs/

name: CI

on:
  push:
    branches: [ main ] # mitä branchia seurataan

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v3

      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }} # asetettu reseptipankki-repon settings -> secrets
        with:
          source-directory: 'express' # minkä kansion sisältö pushataan
          destination-github-username: 'aa3689' # kenen repoon pushataan
          destination-repository-name: 'brita-express' # mihin repoon pushataan
          user-email: aa3689@student.jamk.fi # mihin tulee ilmoitus, jos workflow epäonnistuu
          target-branch: master # mihin branchiin pushataan